//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhvModels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ZhvResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ZhvResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZhvModels.Properties.ZhvResources", typeof(ZhvResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Results representing case roles (retrieved from OpenZaak Web API service) are empty..
        /// </summary>
        public static string HttpRequest_ERROR_EmptyCaseRoles {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_EmptyCaseRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Results representing results about parties (retrieved from OpenKlant Web API service) are empty..
        /// </summary>
        public static string HttpRequest_ERROR_EmptyPartiesResults {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_EmptyPartiesResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTPS protocol is expected..
        /// </summary>
        public static string HttpRequest_ERROR_HttpsProtocolExpected {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_HttpsProtocolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP Request sent to external Web API service failed..
        /// </summary>
        public static string HttpRequest_ERROR_Message {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Any case role (retrieved from OpenZaak Web API service) does not have initiator role matching to the one specified in the project configuration (&apos;OmschrijvingGeneriek&apos;). There is no initiator at all..
        /// </summary>
        public static string HttpRequest_ERROR_MissingInitiatorRole {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_MissingInitiatorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCase {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case details could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseDetails {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case role could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseRole {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case statuses could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseStatuses {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case status type could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseStatusType {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The decision could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDecision {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The decision resource could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDecisionResource {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDecisionResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The decision type could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDecisionType {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDecisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: It was not possible to determine any matching digital addresses (e-mail or phone number) in any of the contact details for any of the parties (citizens, organizations) retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDigitalAddresses {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDigitalAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The documents could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDocuments {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The contact moment could not be retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoFeedbackKlant {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoFeedbackKlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The information object could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoInfoObject {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoInfoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The case (obtained from OpenZaak Web API service) does not contain any statuses..
        /// </summary>
        public static string HttpRequest_ERROR_NoLastStatus {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoLastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The message (object) could not be retrieved from Objecten Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoMessage {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Party results could not be retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoPartyDetails {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoPartyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Party results could not be retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoPartyResults {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoPartyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The notification (from OpenNotificaties Web API service) does not contain source organization (&apos;bronorganisatie&apos;)..
        /// </summary>
        public static string HttpRequest_ERROR_NoSourceOrganization {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoSourceOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The task (object) could not be retrieved from Objecten Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoTask {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVER: The requested resource is unavailable or not existing..
        /// </summary>
        public static string HttpRequest_ERROR_Reason1 {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: The network configuration is improper..
        /// </summary>
        public static string HttpRequest_ERROR_Reason2 {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_Reason2", resourceCulture);
            }
        }
    }
}
