//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhvModels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ZhvResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ZhvResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZhvModels.Properties.ZhvResources", typeof(ZhvResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given JSON cannot be deserialized | Target model: {0} | Failed: {1} | Reason: {2} | All required properties: {3} | Source JSON: {4}.
        /// </summary>
        public static string Deserialization_ERROR_CannotDeserialize_Message {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_CannotDeserialize_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following properties were missing in JSON, but they are required..
        /// </summary>
        public static string Deserialization_ERROR_CannotDeserialize_RequiredProperties {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_CannotDeserialize_RequiredProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON payload is invalid..
        /// </summary>
        public static string Deserialization_ERROR_InvalidJson_Message {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_InvalidJson_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: The input cannot be recognized as JSON format..
        /// </summary>
        public static string Deserialization_ERROR_InvalidJson_Reason1 {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_InvalidJson_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some values of properties in the nested &apos;attributes&apos; (&apos;kenmerken&apos;) in the POCO model are missing..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Attributes_Properties_Message {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Attributes_Properties_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required properties are missing in the given JSON payload..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Notification_Properties_Message {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Notification_Properties_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: In the received notification some [Required] properties are either null, empty, or with default values..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Notification_Properties_Reason1 {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Notification_Properties_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: The standard JSON schema was recently changed and some mandatory properties were removed from it..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Notification_Properties_Reason2 {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Notification_Properties_Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVER: In the POCO model new [Required] properties were added, causing a mismatch with the standard JSON schema..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Notification_Properties_Reason3 {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Notification_Properties_Reason3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received value could not be recognized (might be unexpected)..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Notification_Value_Message {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Notification_Value_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: In the JSON schema some data (value) of property (key) has a different type, format, or is out of range than supported in the POCO model..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Notification_Value_Reason1 {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Notification_Value_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVER: In the POCO model the type, format or range of expected data was recently changed, causing a mismatch with the JSON schema..
        /// </summary>
        public static string Deserialization_ERROR_NotDeserialized_Notification_Value_Reason2 {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_NotDeserialized_Notification_Value_Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON payload contains more root &apos;notification&apos; properties than expected by the POCO model..
        /// </summary>
        public static string Deserialization_ERROR_UnexpectedData_Notification_Message {
            get {
                return ResourceManager.GetString("Deserialization_ERROR_UnexpectedData_Notification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: In the JSON schema some properties from the nested &apos;attributes&apos; (&apos;kenmerken&apos;) are missing, although they were previously defined in the POCO model..
        /// </summary>
        public static string Deserialization_INFO_NotDeserialized_Attributes_Properties_Reason1 {
            get {
                return ResourceManager.GetString("Deserialization_INFO_NotDeserialized_Attributes_Properties_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: In the JSON schema some keys of properties in the nested &apos;attributes&apos; (&apos;kenmerken&apos;) were renamed, causing mismatch with the POCO model..
        /// </summary>
        public static string Deserialization_INFO_NotDeserialized_Attributes_Properties_Reason2 {
            get {
                return ResourceManager.GetString("Deserialization_INFO_NotDeserialized_Attributes_Properties_Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVER: In the POCO model the custom names of some attributes are different from the keys of properties in the nested &apos;attributes&apos; (&apos;kenmerken&apos;) in the received JSON payload..
        /// </summary>
        public static string Deserialization_INFO_NotDeserialized_Attributes_Properties_Reason3 {
            get {
                return ResourceManager.GetString("Deserialization_INFO_NotDeserialized_Attributes_Properties_Reason3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON payload contains more properties in the nested &apos;attributes&apos; (&apos;kenmerken&apos;) than expected by the POCO model..
        /// </summary>
        public static string Deserialization_INFO_UnexpectedData_Attributes_Message {
            get {
                return ResourceManager.GetString("Deserialization_INFO_UnexpectedData_Attributes_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: The JSON schema was recently changed and some properties in the nested &apos;attributes&apos; (&apos;kenmerken&apos;) were added to it..
        /// </summary>
        public static string Deserialization_INFO_UnexpectedData_Attributes_Reason1 {
            get {
                return ResourceManager.GetString("Deserialization_INFO_UnexpectedData_Attributes_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVER: In the POCO model some existing properties were removed from the nested &apos;attributes&apos;, causing a mismatch with the JSON schema..
        /// </summary>
        public static string Deserialization_INFO_UnexpectedData_Attributes_Reason2 {
            get {
                return ResourceManager.GetString("Deserialization_INFO_UnexpectedData_Attributes_Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: The JSON schema was recently changed and some root &apos;notification&apos; properties were added to it..
        /// </summary>
        public static string Deserialization_INFO_UnexpectedData_Notification_Reason1 {
            get {
                return ResourceManager.GetString("Deserialization_INFO_UnexpectedData_Notification_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVER: In the POCO model some existing properties were removed from the root &apos;notification&apos;, causing a mismatch with the JSON schema..
        /// </summary>
        public static string Deserialization_INFO_UnexpectedData_Notification_Reason2 {
            get {
                return ResourceManager.GetString("Deserialization_INFO_UnexpectedData_Notification_Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Results representing case roles (retrieved from OpenZaak Web API service) are empty..
        /// </summary>
        public static string HttpRequest_ERROR_EmptyCaseRoles {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_EmptyCaseRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Results representing results about parties (retrieved from OpenKlant Web API service) are empty..
        /// </summary>
        public static string HttpRequest_ERROR_EmptyPartiesResults {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_EmptyPartiesResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTPS protocol is expected..
        /// </summary>
        public static string HttpRequest_ERROR_HttpsProtocolExpected {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_HttpsProtocolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP Request sent to external Web API service failed..
        /// </summary>
        public static string HttpRequest_ERROR_Message {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Any case role (retrieved from OpenZaak Web API service) does not have initiator role matching to the one specified in the project configuration (&apos;OmschrijvingGeneriek&apos;). There is no initiator at all..
        /// </summary>
        public static string HttpRequest_ERROR_MissingInitiatorRole {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_MissingInitiatorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCase {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case details could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseDetails {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case role could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseRole {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case statuses could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseStatuses {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Case status type could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoCaseStatusType {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoCaseStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The decision could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDecision {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The decision resource could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDecisionResource {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDecisionResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The decision type could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDecisionType {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDecisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: It was not possible to determine any matching digital addresses (e-mail or phone number) in any of the contact details for any of the parties (citizens, organizations) retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDigitalAddresses {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDigitalAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The documents could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoDocuments {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The contact moment could not be retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoFeedbackKlant {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoFeedbackKlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The information object could not be retrieved from OpenZaak Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoInfoObject {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoInfoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The case (obtained from OpenZaak Web API service) does not contain any statuses..
        /// </summary>
        public static string HttpRequest_ERROR_NoLastStatus {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoLastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The message (object) could not be retrieved from Objecten Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoMessage {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Party results could not be retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoPartyDetails {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoPartyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: Party results could not be retrieved from OpenKlant Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoPartyResults {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoPartyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The notification (from OpenNotificaties Web API service) does not contain source organization (&apos;bronorganisatie&apos;)..
        /// </summary>
        public static string HttpRequest_ERROR_NoSourceOrganization {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoSourceOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Request: The task (object) could not be retrieved from Objecten Web API service..
        /// </summary>
        public static string HttpRequest_ERROR_NoTask {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_NoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVER: The requested resource is unavailable or not existing..
        /// </summary>
        public static string HttpRequest_ERROR_Reason1 {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDER: The network configuration is improper..
        /// </summary>
        public static string HttpRequest_ERROR_Reason2 {
            get {
                return ResourceManager.GetString("HttpRequest_ERROR_Reason2", resourceCulture);
            }
        }
    }
}
