//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsHandler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventsHandler.Properties.ApiResources", typeof(ApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1} | Not standardized (unexpected) API response.
        /// </summary>
        internal static string API_Response_ERROR_UnspecifiedResponse {
            get {
                return ResourceManager.GetString("API_Response_ERROR_UnspecifiedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1} | {2}.
        /// </summary>
        internal static string API_Response_STATUS_Logging {
            get {
                return ResourceManager.GetString("API_Response_STATUS_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMC.
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the API was requested..
        /// </summary>
        internal static string Endpoint_Events_Version_INFO_ApiVersionRequested {
            get {
                return ResourceManager.GetString("Endpoint_Events_Version_INFO_ApiVersionRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: v{1} ({2}) | Workflow: v{3} ({4})..
        /// </summary>
        internal static string Endpoint_Events_Version_INFO_OmcVersionsSummary {
            get {
                return ResourceManager.GetString("Endpoint_Events_Version_INFO_OmcVersionsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during processing the notification with ID: {0} | {1}..
        /// </summary>
        internal static string Endpoint_Notify_Confirm_ERROR_UnexpectedFailure {
            get {
                return ResourceManager.GetString("Endpoint_Notify_Confirm_ERROR_UnexpectedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of notification with ID: {0} | {1}..
        /// </summary>
        internal static string Endpoint_Notify_Confirm_INFO_NotificationStatus {
            get {
                return ResourceManager.GetString("Endpoint_Notify_Confirm_INFO_NotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This notification method is not supported..
        /// </summary>
        internal static string Endpoint_Test_Notify_SendEmailSms_ERROR_NotSupportedMethod {
            get {
                return ResourceManager.GetString("Endpoint_Test_Notify_SendEmailSms_ERROR_NotSupportedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} notification was successfully sent to Notify NL..
        /// </summary>
        internal static string Endpoint_Test_Notify_SendEmailSms_SUCCESS_NotificationSent {
            get {
                return ResourceManager.GetString("Endpoint_Test_Notify_SendEmailSms_SUCCESS_NotificationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All required appsettings.json and environment variables are existing and have non-empty values..
        /// </summary>
        internal static string Endpoint_Test_OMC_TestConfigs_SUCCESS_ConfigurationsValid {
            get {
                return ResourceManager.GetString("Endpoint_Test_OMC_TestConfigs_SUCCESS_ConfigurationsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown validation issue occurred..
        /// </summary>
        internal static string Operation_ERROR_Unknown_ValidationIssue_Message {
            get {
                return ResourceManager.GetString("Operation_ERROR_Unknown_ValidationIssue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification was partially recognized/deserialized..
        /// </summary>
        internal static string Operation_SUCCESS_Deserialization_Partial {
            get {
                return ResourceManager.GetString("Operation_SUCCESS_Deserialization_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification was successfully recognized/deserialized..
        /// </summary>
        internal static string Operation_SUCCESS_Deserialization_Success {
            get {
                return ResourceManager.GetString("Operation_SUCCESS_Deserialization_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing aborted..
        /// </summary>
        internal static string Processing_ABORT {
            get {
                return ResourceManager.GetString("Processing_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent because of the confidentiality setting &apos;{0}&apos; in information object related to decision..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_DecisionConfidentiality {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_DecisionConfidentiality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent because the status of the decision is not definitive..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_DecisionStatus {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_DecisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent because the inform field in the case type is set to false..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_Informeren {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_Informeren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent if the task is already closed..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_TaskClosed {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_TaskClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent if the task is not assigned to a person (missing BSN number) or to an organization (missing KVK number)..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_TaskIdTypeNotSupported {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_TaskIdTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent because the case type with identification &apos;{0}&apos; is not included in the {1}..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_Whitelist_CaseTypeId {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_Whitelist_CaseTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent for this object type GUID: {0}. Check respective whitelist (depends on type of your object): {1}..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_Whitelist_GenObjectTypeGuid {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_Whitelist_GenObjectTypeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent for this information object type GUID: {0}, because it is not included in the: {1}..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_Whitelist_InfoObjectType {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_Whitelist_InfoObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification can not be sent because processing messages is forbidden (set to &apos;false&apos;) in the: {0}..
        /// </summary>
        internal static string Processing_ABORT_DoNotSendNotification_Whitelist_MessagesForbidden {
            get {
                return ResourceManager.GetString("Processing_ABORT_DoNotSendNotification_Whitelist_MessagesForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify NL Exception | {0}.
        /// </summary>
        internal static string Processing_ERROR_Exception_Notify {
            get {
                return ResourceManager.GetString("Processing_ERROR_Exception_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1}.
        /// </summary>
        internal static string Processing_ERROR_Exception_Unhandled {
            get {
                return ResourceManager.GetString("Processing_ERROR_Exception_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It wasn&apos;t possible to extract human-friendly error message.
        /// </summary>
        internal static string Processing_ERROR_ExecutingContext_UnknownErrorDetails {
            get {
                return ResourceManager.GetString("Processing_ERROR_ExecutingContext_UnknownErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This controller is not yet registered as handled StandardizeApiResponse.
        /// </summary>
        internal static string Processing_ERROR_ExecutingContext_UnregisteredApiController {
            get {
                return ResourceManager.GetString("Processing_ERROR_ExecutingContext_UnregisteredApiController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test notification was received and ignored..
        /// </summary>
        internal static string Processing_ERROR_Notification_Test {
            get {
                return ResourceManager.GetString("Processing_ERROR_Notification_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no possible to determine URIs of any matching InfoObjects. Continuation of processing the selected notification scenario is pointless..
        /// </summary>
        internal static string Processing_ERROR_Scenario_MissingInfoObjectsURIs {
            get {
                return ResourceManager.GetString("Processing_ERROR_Scenario_MissingInfoObjectsURIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Notify Data to be processed by the selected notification scenario..
        /// </summary>
        internal static string Processing_ERROR_Scenario_MissingNotifyData {
            get {
                return ResourceManager.GetString("Processing_ERROR_Scenario_MissingNotifyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has not been sent to Notify NL: {0}..
        /// </summary>
        internal static string Processing_ERROR_Scenario_NotificationNotSent {
            get {
                return ResourceManager.GetString("Processing_ERROR_Scenario_NotificationNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to determine what to do with the received notification..
        /// </summary>
        internal static string Processing_ERROR_Scenario_NotImplemented {
            get {
                return ResourceManager.GetString("Processing_ERROR_Scenario_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification data were processed successfully by the selected notification scenario..
        /// </summary>
        internal static string Processing_SUCCESS_Scenario_DataProcessed {
            get {
                return ResourceManager.GetString("Processing_SUCCESS_Scenario_DataProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has been successfully processed and sent to Notify NL..
        /// </summary>
        internal static string Processing_SUCCESS_Scenario_NotificationSent {
            get {
                return ResourceManager.GetString("Processing_SUCCESS_Scenario_NotificationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of Besluiten service to be used by OMC is unknown or not supported. Check used version of OMC workflow..
        /// </summary>
        internal static string ServiceResolving_ERROR_VersionBesluitenUnknown {
            get {
                return ResourceManager.GetString("ServiceResolving_ERROR_VersionBesluitenUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of NotifyResponder service to be used by OMC is unknown or not supported. Check used version of OMC workflow..
        /// </summary>
        internal static string ServiceResolving_ERROR_VersionNotifyResponderUnknown {
            get {
                return ResourceManager.GetString("ServiceResolving_ERROR_VersionNotifyResponderUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of Objecten service to be used by OMC is unknown or not supported. Check used version of OMC workflow..
        /// </summary>
        internal static string ServiceResolving_ERROR_VersionObjectenUnknown {
            get {
                return ResourceManager.GetString("ServiceResolving_ERROR_VersionObjectenUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of ObjectTypen service to be used by OMC is unknown or not supported. Check used version of OMC workflow..
        /// </summary>
        internal static string ServiceResolving_ERROR_VersionObjectTypenUnknown {
            get {
                return ResourceManager.GetString("ServiceResolving_ERROR_VersionObjectTypenUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of OpenKlant service to be used by OMC is unknown or not supported. Check used version of OMC workflow..
        /// </summary>
        internal static string ServiceResolving_ERROR_VersionOpenKlantUnknown {
            get {
                return ResourceManager.GetString("ServiceResolving_ERROR_VersionOpenKlantUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of OpenZaak service to be used by OMC is unknown or not supported. Check used version of OMC workflow..
        /// </summary>
        internal static string ServiceResolving_ERROR_VersionOpenZaakUnknown {
            get {
                return ResourceManager.GetString("ServiceResolving_ERROR_VersionOpenZaakUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of Telemetry service to be used by OMC is unknown or not supported. Check used version of OMC workflow..
        /// </summary>
        internal static string ServiceResolving_ERROR_VersionTelemetryUnknown {
            get {
                return ResourceManager.GetString("ServiceResolving_ERROR_VersionTelemetryUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert received JWT token here.
        /// </summary>
        internal static string Swagger_UI_Authentication_Description {
            get {
                return ResourceManager.GetString("Swagger_UI_Authentication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API handling the data and communication workflow between multiple third-party components in order to send notifications through Notify NL..
        /// </summary>
        internal static string Swagger_UI_Description {
            get {
                return ResourceManager.GetString("Swagger_UI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMC (Output Management Component).
        /// </summary>
        internal static string Swagger_UI_Title {
            get {
                return ResourceManager.GetString("Swagger_UI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string Swagger_UI_Version {
            get {
                return ResourceManager.GetString("Swagger_UI_Version", resourceCulture);
            }
        }
    }
}
